name: Deploy to ECR

on: 
  push:
    branches: [main]

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest

    steps:
    
    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1

    - name: Build and push mysql image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: project-mysql
        IMAGE_TAG: v1.0
      run: |
        
        cd docker
        # Docker build
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_DB:$IMAGE_TAG_DB -f Dockerfile_mysql . 
        
        # Unit test
        docker run -d --name mysql -e MYSQL_ROOT_PASSWORD=pw -d $ECR_REGISTRY/$ECR_REPOSITORY_DB:$IMAGE_TAG_DB
        docker ps

        # Docker push to ECR
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
    - name: Build, tag, and push app image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: project-app
        IMAGE_TAG: v1.2
        DBHOST: ${{ secrets.DBHOST }}
        DBPORT: ${{ secrets.DBPORT }}
        DBUSER: ${{ secrets.DBUSER }}
        DBPWD: ${{ secrets.DBPWD }}
        BACKGROUND_IMAGE: 'https://finalbrojectmoishtor.s3.amazonaws.com/wallpaperflare.com_wallpaper.jpg'
      run: |
        
        cd docker
        # Docker build for app image
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile \
          --build-arg DBHOST=$DBHOST \
          --build-arg DBPORT=$DBPORT \
          --build-arg DBUSER=$DBUSER \
          --build-arg DBPWD=$DBPWD \
          --build-arg BACKGROUND_IMAGE=$BACKGROUND_IMAGE .

    - name: Run container for testing
      run: |
        docker run -d -p 8080:8080 \
          -e DBHOST=${{ secrets.DBHOST }} \
          -e DBPORT=${{ secrets.DBPORT }} \
          -e DBUSER=${{ secrets.DBUSER }} \
          -e DBPWD=${{ secrets.DBPWD }} \
          -e BACKGROUND_IMAGE='https://project-s3-g4.s3.amazonaws.com/PJpicture.jpg' \
          --name my_app $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        # Replace the following line with your actual test commands
        echo "Run your tests here. Use curl or other tools to interact with your app."

        # Docker push to ECR
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
